### Load in NumPy (remember to pip install numpy first)

In [1]:
import numpy as np

### The Basics

In [24]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [10]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [16]:
# Get Dimension
a.ndim

1

In [18]:
# Get Shape
b.shape

(2, 3)

In [32]:
# Get Type
a.dtype

dtype('int32')

In [31]:
# Get Size
a.itemsize
#int32 matlab 00000000 00000000 00000000 00000101 jaisa hoga to 4 bytes ho gaye(4 bytes= 32 bits) 

4

In [29]:
# Get total size
a.nbytes

12

In [35]:
# Get number of elements
a.size

3

In [96]:
r=np.arange(15)
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [98]:
l=np.linspace(1,5,12)
l
#This will create an array with 12 elements between 1 and 5 which have equal difference between them

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [103]:
emp= np.empty((3,2))
emp
#This creates array of random values without initializing any random value

array([[2.64575131, 1.        ],
       [2.82842712, 1.73205081],
       [2.        , 0.        ]])

In [99]:
v = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
v

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [100]:
v=v.ravel()
v
#Ravel converts anything into a 1D array

array([1, 2, 3, 4, 5, 6, 7, 8])

### Accessing/Changing specific elements, rows, columns, etc

In [45]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [14]:
# Get a specific element [r, c]
a[1, 5]
#It starts with 0 so 2nd row would be 1

13

In [15]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
# Get a specific column
a[:, 2]
#Iska matlab yeh hai ki ek column yaani 3 aur 10 aa gaye(socho)

array([ 3, 10])

In [20]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]
#Iska matlab pehli row mai aap start karo 2nd se aur end karo -1 yaani 2nd last row se( kyuki yeh exclusive hota hai to yeh yaha
#second last row ko refer kar raha hai), with the difference of 2 elements

array([2, 4, 6])

In [24]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

#Pehle kisis column ko 5 kiya tha isliye pehle waale array ko ignore maaro

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [25]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [30]:
# Get specific element (work outside in)
b[0,1,1]

4

In [19]:
# replace 
b[:,1,:] = [[9,9],[8,8]]

In [20]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing Different Types of Arrays

In [40]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [44]:
# Any other number
np.full((2,2), 99)

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [49]:
# Any other number (full_like)
np.full_like(a, 4)
#The numpy.full_like() function return a new array with the same shape and type as a given array.

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [56]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.07805642, 0.53385716],
       [0.02494273, 0.99955252],
       [0.48588042, 0.91247437],
       [0.27779213, 0.16597751]])

In [73]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))
#Here the low (-4) is incusive and the high(8) is exclusive

array([[-2, -4, -4],
       [ 6,  6,  3],
       [ 3,  2,  2]])

In [76]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)
print("\n")
r2 = np.repeat(arr,3, axis=1)
print(r2)
#The concept is we take an array and are repeating it three times
#The axis specified tells us how it is being repeated

[[1 2 3]
 [1 2 3]
 [1 2 3]]


[[1 1 1 2 2 2 3 3 3]]


In [89]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


###### Be careful when copying arrays!!!

In [98]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


### Mathematics

In [74]:
[2,3] + [4,6]
#Normal python does not lets us perform operations on matrix but numpy lets us do just that

[2, 3, 4, 6]

In [75]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [76]:
a + 2

array([3, 4, 5, 6])

In [77]:
a - 2

array([-1,  0,  1,  2])

In [78]:
a * 2

array([2, 4, 6, 8])

In [79]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [80]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [81]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [82]:
# Take the sin
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [90]:
c = np.random.randint(0,9,size=(2,3))
c

array([[7, 1, 8],
       [3, 4, 0]])

In [91]:
np.where(c>5)

(array([0, 0], dtype=int64), array([0, 2], dtype=int64))

In [92]:
np.sqrt(c)

array([[2.64575131, 1.        , 2.82842712],
       [1.73205081, 2.        , 0.        ]])

In [93]:
np.count_nonzero(c)

5

In [94]:
np.nonzero(c)

(array([0, 0, 0, 1, 1], dtype=int64), array([0, 1, 2, 0, 1], dtype=int64))

In [104]:
q=np.empty_like(c)
q
# Return a new array with the same shape and type as a given array

array([[-1067323344,         446,           0],
       [          0,           1,     6553706]])

In [117]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [127]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [132]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [133]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [66]:
stats = np.random.randint(3,14,size=(3,4))
stats

array([[ 8,  6,  4,  4],
       [10,  4, 13,  8],
       [ 7,  7, 13, 13]])

In [67]:
stats.max()

13

In [68]:
stats.argmax()
#Gives the index of maximum number

6

In [69]:
np.min(stats)

4

In [70]:
np.argmin(stats)

2

In [71]:
np.max(stats, axis=1)

array([ 8, 13, 13])

In [72]:
np.sum(stats, axis=0)

array([25, 17, 30, 25])

In [73]:
stats.argsort()
#What this does is arranges the numbers in ascending order and gives their original indexes

array([[2, 3, 1, 0],
       [1, 3, 0, 2],
       [0, 1, 2, 3]], dtype=int64)

### Reorganizing Arrays

In [48]:
c=np.random.randint(3,9,size=(4,6))
print(c)
print("\n\n")
d=c.T
print(d)
#Transpose

[[5 8 7 6 6 7]
 [7 6 7 3 6 5]
 [4 3 5 4 5 5]
 [4 5 7 8 3 7]]



[[5 7 4 4]
 [8 6 3 5]
 [7 7 5 7]
 [6 3 4 8]
 [6 6 5 3]
 [7 5 5 7]]


In [43]:
array = np.arange(15).reshape(3, 5)
print("2D array : \n",array )
 
print("\nID array : \n", array.flat[0:15])        
 
print("\nType of array,flat() : ", type(array.flat))
 
for i in array.flat:
    print(i, end = ' ')
#Used for iterating

2D array : 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

ID array : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

Type of array,flat() :  <class 'numpy.flatiter'>
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 

In [27]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [158]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [164]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
##### Load Data from File

In [28]:
filedata = np.genfromtxt('C:/Users/Lenovo/Desktop/datasets/NumPy-master/data.txt', delimiter=',')

#delimiter : The string used to separate values. By default, this is any whitespace.
#[[ 0  1  2]
#[ 3  4  5]]

filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### Boolean Masking and Advanced Indexing

In [29]:
filedata > 50

#All those which thier values above 50 will be true

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [32]:
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [33]:
#You can index with a list in numpy

a=np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [37]:
np.any(filedata>50,axis=0)

#axis=0 matlab columns mai koi bhi agar above 50 ho to true dedo

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [38]:
np.any(filedata>50,axis=1)
#axis=1 matlab rows mai koi bhi agar above 50 ho to true dedo

array([ True,  True,  True])

In [39]:
np.all(filedata>50,axis=0)
# isme agar sabhi 50 ke upar nahi ho to false de dega

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [40]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [196]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

# gfsajhdgahfgajs